/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.prism.impl.PrismSettings;
import gestorproyectos.Pieza;
import gestorproyectos.Proveedor;
import gestorproyectos.Proyecto;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 9fad08
 */
public class GestionDatos extends javax.swing.JFrame {

    /**
     * Creates new form GestionDatos
     */
    /*   public GestionDatos() {
        initComponents();
        
    }*/
    public GestionDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_prov = new javax.swing.JPanel();
        lbl_codigo1 = new javax.swing.JLabel();
        lbl_nombre1 = new javax.swing.JLabel();
        lbl_ape1 = new javax.swing.JLabel();
        lbl_direc1 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_ape = new javax.swing.JTextField();
        tf_direc = new javax.swing.JTextField();
        lbl_ciudad = new javax.swing.JLabel();
        tf_ciudad = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        lbl_precio = new javax.swing.JLabel();
        tf_descrip = new javax.swing.JTextField();
        lbl_descrip = new javax.swing.JLabel();
        btn_insert = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_prov1 = new javax.swing.JPanel();
        lbl_codigo2 = new javax.swing.JLabel();
        lbl_nombre2 = new javax.swing.JLabel();
        lbl_ape2 = new javax.swing.JLabel();
        lbl_direc2 = new javax.swing.JLabel();
        tf_codigo1 = new javax.swing.JTextField();
        tf_nombre1 = new javax.swing.JTextField();
        tf_ape1 = new javax.swing.JTextField();
        tf_direc1 = new javax.swing.JTextField();
        lbl_ciudad1 = new javax.swing.JLabel();
        tf_ciudad1 = new javax.swing.JTextField();
        tf_precio1 = new javax.swing.JTextField();
        lbl_precio1 = new javax.swing.JLabel();
        tf_descrip1 = new javax.swing.JTextField();
        lbl_descrip1 = new javax.swing.JLabel();
        btn_ejecutar = new javax.swing.JButton();
        btn_baja = new javax.swing.JButton();
        lbl_reg_actual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_reg_total = new javax.swing.JLabel();
        btn_primero = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ALTAS, BAJAS Y MODIFICACIONES");

        lbl_codigo1.setText("Código");
        lbl_codigo1.setToolTipText("");

        lbl_nombre1.setText("Nombre");

        lbl_ape1.setText("Apellidos");

        lbl_direc1.setText("Dirección");

        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });
        tf_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codigoKeyPressed(evt);
            }
        });

        tf_direc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_direcActionPerformed(evt);
            }
        });

        lbl_ciudad.setText("Ciudad");

        lbl_precio.setText("Precio");

        tf_descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_descripActionPerformed(evt);
            }
        });

        lbl_descrip.setText("Descripción");

        javax.swing.GroupLayout panel_provLayout = new javax.swing.GroupLayout(panel_prov);
        panel_prov.setLayout(panel_provLayout);
        panel_provLayout.setHorizontalGroup(
            panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_provLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre1)
                    .addComponent(lbl_ape1)
                    .addComponent(lbl_direc1)
                    .addComponent(lbl_precio)
                    .addComponent(lbl_descrip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_descrip)
                    .addComponent(tf_precio)
                    .addComponent(tf_nombre)
                    .addComponent(tf_ape)
                    .addGroup(panel_provLayout.createSequentialGroup()
                        .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_ciudad)
                        .addGap(18, 18, 18)
                        .addComponent(tf_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addComponent(tf_direc))
                .addContainerGap())
        );
        panel_provLayout.setVerticalGroup(
            panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_provLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_provLayout.createSequentialGroup()
                        .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_provLayout.createSequentialGroup()
                                .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_codigo1)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ciudad)
                                    .addComponent(tf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbl_nombre1))
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ape1))
                    .addComponent(tf_ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_direc1)
                    .addComponent(tf_direc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panel_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_descrip))
                .addContainerGap())
        );

        btn_insert.setText("Insertar");

        btn_update.setText("Modificar");
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });

        btn_limpiar.setText("Limpiar");

        btn_delete.setText("Eliminar");
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addComponent(panel_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(btn_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(panel_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btn_limpiar)
                        .addGap(27, 27, 27)
                        .addComponent(btn_insert)
                        .addGap(29, 29, 29)
                        .addComponent(btn_update)
                        .addGap(29, 29, 29)
                        .addComponent(btn_delete)))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Gestión", tab1);

        jLabel2.setText("ALTAS, BAJAS Y MODIFICACIONES");

        lbl_codigo2.setText("Código");
        lbl_codigo2.setToolTipText("");

        lbl_nombre2.setText("Nombre");

        lbl_ape2.setText("Apellidos");

        lbl_direc2.setText("Dirección");

        tf_direc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_direc1ActionPerformed(evt);
            }
        });

        lbl_ciudad1.setText("Ciudad");

        lbl_precio1.setText("Precio");

        tf_descrip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_descrip1ActionPerformed(evt);
            }
        });

        lbl_descrip1.setText("Descripción");

        javax.swing.GroupLayout panel_prov1Layout = new javax.swing.GroupLayout(panel_prov1);
        panel_prov1.setLayout(panel_prov1Layout);
        panel_prov1Layout.setHorizontalGroup(
            panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_prov1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_codigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre2)
                    .addComponent(lbl_ape2)
                    .addComponent(lbl_direc2)
                    .addComponent(lbl_precio1)
                    .addComponent(lbl_descrip1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_descrip1)
                    .addComponent(tf_precio1)
                    .addComponent(tf_nombre1)
                    .addComponent(tf_ape1)
                    .addGroup(panel_prov1Layout.createSequentialGroup()
                        .addComponent(tf_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_ciudad1)
                        .addGap(18, 18, 18)
                        .addComponent(tf_ciudad1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addComponent(tf_direc1))
                .addContainerGap())
        );
        panel_prov1Layout.setVerticalGroup(
            panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_prov1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_prov1Layout.createSequentialGroup()
                        .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_prov1Layout.createSequentialGroup()
                                .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_codigo2)
                                    .addComponent(tf_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ciudad1)
                                    .addComponent(tf_ciudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbl_nombre2))
                            .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ape2))
                    .addComponent(tf_ape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_direc2)
                    .addComponent(tf_direc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_precio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panel_prov1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_descrip1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_descrip1))
                .addContainerGap())
        );

        btn_ejecutar.setText("Ejecutar consulta");
        btn_ejecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ejecutarMouseClicked(evt);
            }
        });

        btn_baja.setText("Baja");
        btn_baja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bajaMouseClicked(evt);
            }
        });

        lbl_reg_actual.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("/");

        lbl_reg_total.setText("jLabel5");

        btn_primero.setText("<<");
        btn_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_primeroMouseClicked(evt);
            }
        });

        btn_anterior.setText("<");
        btn_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anteriorMouseClicked(evt);
            }
        });

        btn_siguiente.setText(">");
        btn_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_siguienteMouseClicked(evt);
            }
        });

        btn_ultimo.setText(">>");
        btn_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ultimoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(panel_prov1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_ejecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(btn_baja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2)))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(btn_primero)
                                .addGap(18, 18, 18)
                                .addComponent(btn_anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_siguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ultimo))
                            .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(lbl_reg_actual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_reg_total)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel_prov1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_baja, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_reg_actual)
                    .addComponent(jLabel4)
                    .addComponent(lbl_reg_total))
                .addGap(34, 34, 34)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_primero)
                    .addComponent(btn_anterior)
                    .addComponent(btn_siguiente)
                    .addComponent(btn_ultimo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Listado", tab2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_direcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_direcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_direcActionPerformed

    private void tf_descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_descripActionPerformed

    private void tf_direc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_direc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_direc1ActionPerformed

    private void tf_descrip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_descrip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_descrip1ActionPerformed

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoActionPerformed

    private void tf_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Enter was pressed. Your code goes here.
            obtenerRegistro();
        }
    }//GEN-LAST:event_tf_codigoKeyPressed

    private void btn_ejecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ejecutarMouseClicked
        // TODO add your handling code here:
        contador = 0;
        iniciarControles(opcion, contador);
    }//GEN-LAST:event_btn_ejecutarMouseClicked

    private void btn_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_primeroMouseClicked
        // TODO add your handling code here:
        // ir al primer registro
        contador = 0;
        iniciarControles(opcion, contador);
    }//GEN-LAST:event_btn_primeroMouseClicked

    private void btn_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anteriorMouseClicked
        // TODO add your handling code here:
        if (contador > 0) {
            contador--;
        }
        iniciarControles(opcion, contador);
    }//GEN-LAST:event_btn_anteriorMouseClicked

    private void btn_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguienteMouseClicked
        // TODO add your handling code here:
        if (contador < total_registros - 1) {
            contador++;
        }
        iniciarControles(opcion, contador);
    }//GEN-LAST:event_btn_siguienteMouseClicked

    private void btn_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ultimoMouseClicked
        // TODO add your handling code here:
        contador = total_registros - 1;
        iniciarControles(opcion, contador);
    }//GEN-LAST:event_btn_ultimoMouseClicked

    private void btn_bajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bajaMouseClicked
        // TODO add your handling code here:

        // ELIMINAR REGISTRO
        String codigo = tf_codigo1.getText();
        int filas = 0;
        try {
            filas = eliminarRegistro(codigo);
        } catch (SQLException ex) {
            Logger.getLogger(GestionDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (filas > 0) {
            if (contador > 0) {
                contador--;
            }
            iniciarControles(opcion, contador);
        }
    }//GEN-LAST:event_btn_bajaMouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        // TODO add your handling code here:
        
        // ELIMINAR REGISTRO
        String codigo = tf_codigo.getText();
        int filas = 0;
        try {
            filas = eliminarRegistro(codigo);
        } catch (SQLException ex) {
            Logger.getLogger(GestionDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (filas > 0) {
            if (contador > 0) {
                contador--;
            }
            iniciarControles(opcion, contador);
        }
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        // TODO add your handling code here:
        String codigo = tf_codigo.getText();
        int filas = 0;
        try {
            filas = modificarRegistro(codigo);
        } catch (SQLException ex) {
            Logger.getLogger(GestionDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_updateMouseClicked

    /*
    *   MÉTODOS
     */
    public void opcion(String o) throws SQLException {
        this.opcion = o.toUpperCase();
        switch (this.opcion) {
            case "PROVEEDOR":
                this.setTitle("Proveedores");
                // campos proyecto
                ocultarProyecto();
                // campos pieza
                ocultarPieza();
                // obtener datos
                obtenerProveedores();
                break;
            case "PIEZA":
                this.setTitle("Piezas");
                // campos proveedor
                ocultarProveedor();
                // campos proyecto
                ocultarProyecto();
                // obtener datos
                obtenerPiezas();
                break;
            case "PROYECTO":
                this.setTitle("Proyectos");
                // campos proveedor
                ocultarProveedor();
                // campos pieza
                ocultarPieza();
                // obtener datos
                obtenerProyectos();
                break;
            default:
                break;
        }
    }

    private void ocultarProveedor() {
        this.lbl_ape1.setVisible(false);
        this.tf_ape.setVisible(false);
        this.lbl_direc1.setVisible(false);
        this.tf_direc.setVisible(false);
        this.lbl_ape2.setVisible(false);
        this.tf_ape1.setVisible(false);
        this.lbl_direc2.setVisible(false);
        this.tf_direc1.setVisible(false);
    }

    private void ocultarPieza() {
        this.lbl_precio.setVisible(false);
        this.tf_precio.setVisible(false);
        this.lbl_descrip.setVisible(false);
        this.tf_descrip.setVisible(false);
        this.lbl_precio1.setVisible(false);
        this.tf_precio1.setVisible(false);
        this.lbl_descrip1.setVisible(false);
        this.tf_descrip1.setVisible(false);
    }

    private void ocultarProyecto() {
        this.lbl_ciudad.setVisible(false);
        this.tf_ciudad.setVisible(false);
        this.lbl_ciudad1.setVisible(false);
        this.tf_ciudad1.setVisible(false);
    }

    private void obtenerProveedores() throws SQLException {
        if (this.con != null) {

            // Preparamos la consulta
            Statement sentencia = (Statement) con.createStatement();
            ResultSet result = sentencia.executeQuery("SELECT * FROM proveedor");
            lista_proveedores = new ArrayList<>();
            while (result.next()) {
                Proveedor p = new Proveedor();
                p.setCodigo(result.getString("codigo"));
                p.setNombre(result.getString("nombre"));
                p.setApellido(result.getString("apellidos"));
                p.setDireccion(result.getString("direccion"));
                lista_proveedores.add(p);

            }
            this.total_registros = lista_proveedores.size();
            //     System.out.println(total_registros);
            result.close();
            sentencia.close();

        }
    }

    private void obtenerPiezas() throws SQLException {
        if (this.con != null) {

            // Preparamos la consulta
            Statement sentencia = (Statement) con.createStatement();
            ResultSet result = sentencia.executeQuery("SELECT * FROM pieza");
            lista_piezas = new ArrayList<>();
            while (result.next()) {
                Pieza p = new Pieza();
                p.setCodigo(result.getString("codigo"));
                p.setNombre(result.getString("nombre"));
                p.setPrecio(result.getFloat("precio"));
                p.setDescripcion(result.getString("descripcion"));
                lista_piezas.add(p);

            }
            this.total_registros = lista_piezas.size();
            result.close();
            sentencia.close();

        }
    }

    private void obtenerProyectos() throws SQLException {
        if (this.con != null) {

            // Preparamos la consulta
            Statement sentencia = (Statement) con.createStatement();
            ResultSet result = sentencia.executeQuery("SELECT * FROM proyecto");
            lista_proyectos = new ArrayList<>();
            while (result.next()) {
                Proyecto p = new Proyecto();
                p.setCodigo(result.getString("codigo"));
                p.setNombre(result.getString("nombre"));
                p.setCiudad(result.getString("ciudad"));
                lista_proyectos.add(p);

            }
            this.total_registros = lista_proyectos.size();
            result.close();
            sentencia.close();

        }
    }

    private void iniciarControles(String o, int indice) {
        switch (o) {
            case "PROVEEDOR":
                // DATOS DE LA PESTAÑA 2 QUE SE MOSTRARÁN POR DEFECTO (el primer registro)
                Proveedor p = lista_proveedores.get(indice);
                tf_codigo1.setText(p.getCodigo());
                tf_nombre1.setText(p.getNombre());
                tf_ape1.setText(p.getApellido());
                tf_direc1.setText(p.getDireccion());
                break;
            case "PIEZA":
                // DATOS DE LA PESTAÑA 2 QUE SE MOSTRARÁN POR DEFECTO (el primer registro)
                Pieza pi = lista_piezas.get(indice);
                tf_codigo1.setText(pi.getCodigo());
                tf_nombre1.setText(pi.getNombre());
                tf_precio1.setText(String.valueOf(pi.getPrecio()));
                tf_descrip1.setText(pi.getDescripcion());

                break;
            case "PROYECTO":
                // DATOS DE LA PESTAÑA 2 QUE SE MOSTRARÁN POR DEFECTO (el primer registro)
                Proyecto po = lista_proyectos.get(indice);
                tf_codigo1.setText(po.getCodigo());
                tf_nombre1.setText(po.getNombre());
                tf_ciudad1.setText(po.getCiudad());
                break;
            default:
                break;
        }
    }

    private void obtenerRegistro() {

        switch (this.opcion) {
            case "PROVEEDOR":
                // DATOS DE LA PESTAÑA 1 si encuentre el codigo
                for (Proveedor p : lista_proveedores) {
                    if (p.getCodigo().equalsIgnoreCase(tf_codigo.getText())) {
                        tf_nombre.setText(p.getNombre());
                        tf_ape.setText(p.getApellido());
                        tf_direc.setText(p.getDireccion());
                        break;
                    }
                }

                break;
            case "PIEZA":
                // DATOS DE LA PESTAÑA 1 si encuentre el codigo
                for (Pieza p : lista_piezas) {
                    if (p.getCodigo().equalsIgnoreCase(tf_codigo.getText())) {
                        tf_nombre.setText(p.getNombre());
                        tf_precio1.setText(String.valueOf(p.getPrecio()));
                        tf_descrip1.setText(p.getDescripcion());
                        break;
                    }
                }
                break;
            case "PROYECTO":
                // DATOS DE LA PESTAÑA 1 si encuentre el codigo
                for (Proyecto p : lista_proyectos) {
                    if (p.getCodigo().equalsIgnoreCase(tf_codigo.getText())) {
                        tf_nombre.setText(p.getNombre());
                        tf_ciudad1.setText(p.getCiudad());
                        break;
                    }
                }

                break;
            default:
                break;
        }
    }

    private int eliminarRegistro(String codigo) throws SQLException {

        int filas = 0;
        switch (this.opcion) {
            case "PROVEEDOR":
                for (Proveedor p : lista_proveedores) {
                    if (p.getCodigo().equalsIgnoreCase(codigo)) {

                        String sql = "DELETE FROM proveedor WHERE codigo = ?";
                        PreparedStatement sentencia = con.prepareStatement(sql);
                        sentencia.setString(1, codigo);
                        filas = sentencia.executeUpdate();
                        if (filas > 0) {
                            lista_proveedores.remove(p);
                        }
                        break;
                    }
                }
                break;
            case "PIEZA":
                for (Pieza p : lista_piezas) {
                    if (p.getCodigo().equalsIgnoreCase(codigo)) {
                        String sql = "DELETE FROM pieza WHERE codigo = ?";
                        PreparedStatement sentencia = con.prepareStatement(sql);
                        sentencia.setString(1, codigo);
                        filas = sentencia.executeUpdate();
                        if (filas > 0) {
                            lista_piezas.remove(p);
                        }
                        break;
                    }
                }
                break;
            case "PROYECTO":
                for (Proyecto p : lista_proyectos) {
                    if (p.getCodigo().equalsIgnoreCase(codigo)) {
                        String sql = "DELETE FROM proyecto WHERE codigo = ?";
                        PreparedStatement sentencia = con.prepareStatement(sql);
                        sentencia.setString(1, codigo);
                        filas = sentencia.executeUpdate();
                        if (filas > 0) {
                            lista_proyectos.remove(p);
                        }
                        break;
                    }
                }
                break;
            default:
                break;
        }
        return filas;
    }
    
    private int modificarRegistro(String codigo) throws SQLException{
        
        int filas = 0;
        switch (this.opcion) {
            case "PROVEEDOR":
                for (Proveedor p : lista_proveedores) {
                    if (p.getCodigo().equalsIgnoreCase(codigo)) {

                        String sql = "update proveedor set nombre = ?, apellidos = ?, direccion = ? where codigo = ?";
                        PreparedStatement sentencia = con.prepareStatement(sql);
                        sentencia.setString(1, tf_nombre.getText());
                        sentencia.setString(2, tf_ape.getText());
                        sentencia.setString(3, tf_direc.getText());
                        sentencia.setString(4, codigo);
                        filas = sentencia.executeUpdate();
                        if (filas > 0) {
                            p.setNombre(tf_nombre.getText());
                            p.setApellido(tf_ape.getText());
                            p.setDireccion(tf_direc.getText());
                        }
                        break;
                    }
                }
                break;
            case "PIEZA":
             /*   for (Pieza p : lista_piezas) {
                    if (p.getCodigo().equalsIgnoreCase(codigo)) {
                        String sql = "DELETE FROM pieza WHERE codigo = ?";
                        PreparedStatement sentencia = con.prepareStatement(sql);
                        sentencia.setString(1, codigo);
                        filas = sentencia.executeUpdate();
                        if (filas > 0) {
                            lista_piezas.remove(p);
                        }
                        break;
                    }
                }*/
                break;
            case "PROYECTO":
            /*    for (Proyecto p : lista_proyectos) {
                    if (p.getCodigo().equalsIgnoreCase(codigo)) {
                        String sql = "DELETE FROM proyecto WHERE codigo = ?";
                        PreparedStatement sentencia = con.prepareStatement(sql);
                        sentencia.setString(1, codigo);
                        filas = sentencia.executeUpdate();
                        if (filas > 0) {
                            lista_proyectos.remove(p);
                        }
                        break;
                    }
                }*/
                break;
            default:
                break;
        }
        return filas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDatos().setVisible(true);
            }
        });
    }

    private String opcion;
    private Connection con;
    private List<Proveedor> lista_proveedores;
    private List<Pieza> lista_piezas;
    private List<Proyecto> lista_proyectos;
    private int contador;
    private int total_registros;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_baja;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_primero;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_ape1;
    private javax.swing.JLabel lbl_ape2;
    private javax.swing.JLabel lbl_ciudad;
    private javax.swing.JLabel lbl_ciudad1;
    private javax.swing.JLabel lbl_codigo1;
    private javax.swing.JLabel lbl_codigo2;
    private javax.swing.JLabel lbl_descrip;
    private javax.swing.JLabel lbl_descrip1;
    private javax.swing.JLabel lbl_direc1;
    private javax.swing.JLabel lbl_direc2;
    private javax.swing.JLabel lbl_nombre1;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_precio1;
    private javax.swing.JLabel lbl_reg_actual;
    private javax.swing.JLabel lbl_reg_total;
    private javax.swing.JPanel panel_prov;
    private javax.swing.JPanel panel_prov1;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JTextField tf_ape;
    private javax.swing.JTextField tf_ape1;
    private javax.swing.JTextField tf_ciudad;
    private javax.swing.JTextField tf_ciudad1;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_codigo1;
    private javax.swing.JTextField tf_descrip;
    private javax.swing.JTextField tf_descrip1;
    private javax.swing.JTextField tf_direc;
    private javax.swing.JTextField tf_direc1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param con the con to set
     */
    public void setCon(Connection con) {
        this.con = con;
    }
}
